version: "3.7"

services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: always
    network_mode: host
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /autobrr/config:/config
    ports:
      - 7474:7474
