version: "3.7"

services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: always
    environment:
      - TZ=America/Los_Angeles
    user: 1000:1000
    volumes:
      - /autobrr/config:/config
    ports:
      - 7474:7474
#You May Need to Add the container created to the "bridge" network.
#Dont Forget to reboot conatiner so it gets a IP Address.
